name: my-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_CONNECTION: sqlite
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:gen --ansi
      - name: Prepare database
        run: php artisan migrate:fresh --seed
      - name: Check linter
        run: composer exec --verbose phpcs -- --standard=PSR12 app config routes
      - name: Check phpstan
        run: composer exec phpstan analyse
      - name: Launch tests
        run: php artisan test